//! Generate Rust bindings for the pinned FFmpeg version.
//!
//! Usage: gen-ffmpeg-bindings <ffmpeg-include-dir> <out.rs> [-I<extra include dir> ...]
//!
//! The result is committed so normal builds need neither libclang nor bindgen.

use anyhow::{bail, Result};

const WRAPPER: &str = r#"
#include <libavcodec/avcodec.h>
#include <libavutil/hwcontext.h>
#include <libavutil/opt.h>
#include <libavutil/pixdesc.h>
#include <libavutil/imgutils.h>
#include <libavutil/channel_layout.h>
#include <libavutil/error.h>
#include <libavutil/log.h>
"#;

fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    if args.len() < 2 {
        bail!("usage: gen-ffmpeg-bindings <ffmpeg-include-dir> <out.rs> [-I<dir> ...]");
    }
    let mut clang_args = vec![
        format!("-I{}", args[0]),
        "--target=x86_64-pc-windows-msvc".to_string(),
        "-fms-compatibility".to_string(),
        "-fms-extensions".to_string(),
    ];
    clang_args.extend(args[2..].iter().cloned());

    let bindings = bindgen::Builder::default()
        .header_contents("wrapper.h", WRAPPER)
        .clang_args(clang_args)
        .allowlist_function("av_.*|avcodec_.*|avutil_.*")
        .allowlist_type("AV.*")
        .allowlist_var("AV_.*|AVERROR_.*|FF_.*|LIBAVCODEC_.*|LIBAVUTIL_.*")
        // Constants instead of Rust enums: a newer DLL may return values we don't know.
        .default_enum_style(bindgen::EnumVariation::Consts)
        .prepend_enum_name(false)
        .layout_tests(false)
        .derive_default(true)
        .generate_comments(false)
        .raw_line("// Generated by tools/gen-ffmpeg-bindings. Do not edit.")
        .raw_line("#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code, clippy::all)]")
        .generate()?;
    bindings.write_to_file(&args[1])?;
    eprintln!("wrote {}", args[1]);
    Ok(())
}
