//! Raw FFmpeg bindings for the pinned version (8.1, libavcodec 62 / libavutil 60).
//!
//! `bindings.rs` is generated by `tools/gen-ffmpeg-bindings`; items that are C
//! macros or need Windows headers are defined by hand below.

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]

mod bindings;
pub use bindings::*;

use std::os::raw::{c_int, c_void};

/// Major versions the bindings were generated for; checked at runtime.
pub const EXPECTED_AVCODEC_MAJOR: u32 = 62;
pub const EXPECTED_AVUTIL_MAJOR: u32 = 60;

const fn fferrtag(a: u8, b: u8, c: u8, d: u8) -> c_int {
    -((a as c_int) | ((b as c_int) << 8) | ((c as c_int) << 16) | ((d as c_int) << 24))
}

pub const AVERROR_EOF: c_int = fferrtag(b'E', b'O', b'F', b' ');
pub const AVERROR_EXPERIMENTAL: c_int = -0x2bb2_afa8;
/// `AVERROR(EAGAIN)`; EAGAIN is 11 in both the MSVC and MinGW CRTs.
pub const AVERROR_EAGAIN: c_int = -11;
/// `AVERROR(ENOMEM)`
pub const AVERROR_ENOMEM: c_int = -12;
/// `AVERROR(EINVAL)`
pub const AVERROR_EINVAL: c_int = -22;
/// `AVERROR(ENOSYS)`
pub const AVERROR_ENOSYS: c_int = -40;

pub const AV_NOPTS_VALUE: i64 = i64::MIN;

/// `libavutil/hwcontext_d3d11va.h` — COM pointers are opaque here.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct AVD3D11VADeviceContext {
    pub device: *mut c_void,
    pub device_context: *mut c_void,
    pub video_device: *mut c_void,
    pub video_context: *mut c_void,
    pub lock: Option<unsafe extern "C" fn(lock_ctx: *mut c_void)>,
    pub unlock: Option<unsafe extern "C" fn(lock_ctx: *mut c_void)>,
    pub lock_ctx: *mut c_void,
    pub BindFlags: u32,
    pub MiscFlags: u32,
}

#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct AVD3D11FrameDescriptor {
    pub texture: *mut c_void,
    pub index: isize,
}

#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct AVD3D11VAFramesContext {
    pub texture: *mut c_void,
    pub BindFlags: u32,
    pub MiscFlags: u32,
    pub texture_infos: *mut AVD3D11FrameDescriptor,
}

/// `libavutil/hwcontext_qsv.h` — mfx structures are opaque here.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct AVQSVFramesContext {
    pub surfaces: *mut c_void,
    pub nb_surfaces: c_int,
    /// `MFX_MEMTYPE_*` flags; decides the D3D11 bind flags of the child textures.
    pub frame_type: c_int,
    pub info: *mut c_void,
}

/// `MFX_MEMTYPE_VIDEO_MEMORY_DECODER_TARGET`
pub const MFX_MEMTYPE_VIDEO_MEMORY_DECODER_TARGET: c_int = 0x0010;
/// `MFX_MEMTYPE_VIDEO_MEMORY_PROCESSOR_TARGET` — child D3D11 textures get `D3D11_BIND_RENDER_TARGET`.
pub const MFX_MEMTYPE_VIDEO_MEMORY_PROCESSOR_TARGET: c_int = 0x0020;

/// `D3D11_BIND_SHADER_RESOURCE` / `D3D11_BIND_RENDER_TARGET` / `D3D11_BIND_DECODER`
pub const D3D11_BIND_SHADER_RESOURCE: u32 = 0x8;
pub const D3D11_BIND_RENDER_TARGET: u32 = 0x20;
pub const D3D11_BIND_DECODER: u32 = 0x200;

/// Human readable text for an FFmpeg error code.
pub fn err_to_string(err: c_int) -> String {
    let mut buf = [0 as std::os::raw::c_char; 256];
    unsafe {
        av_strerror(err, buf.as_mut_ptr(), buf.len());
        std::ffi::CStr::from_ptr(buf.as_ptr()).to_string_lossy().into_owned()
    }
}

/// Runtime DLL versions as (avcodec major, avutil major).
pub fn runtime_versions() -> (u32, u32) {
    unsafe { (avcodec_version() >> 16, avutil_version() >> 16) }
}
